Get and use prebuilt LLVM for CI build

diff --git a/.github/workflows/build-methods.yml b/.github/workflows/build-methods.yml
--- a/.github/workflows/build-methods.yml
+++ b/.github/workflows/build-methods.yml
@@ -55,7 +55,68 @@ jobs:
         body: |
           Verifying build methods work: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
-  # super-build: -- Done as part of the checks.yml file
+  super-build:
+    needs: comment-triggered
+    runs-on: ubuntu-18.04
+    if: needs.comment-triggered.outputs.checks_should_run == 'true'
+
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - run: |
+        echo ${{ github.token }} | gh auth login --with-token
+        gh pr checkout ${{ github.event.issue.number }}
+      if: needs.comment-triggered.outputs.value == 'true'
+
+    - name: Install dependencies
+      run: |
+        sudo apt-get install ninja-build
+        sudo apt-get install ccache
+
+    - name: Set up ccache
+      uses: actions/cache@v1.1.0
+      with:
+        path: .ccache
+        key: ccache-super
+
+    - run: |
+        ccache -o hash_dir=false
+
+    - name: Configure
+      run: |
+        mkdir build-ci && cd build-ci
+
+        # Release build because Debug builds run out of memory.
+        # ccache greatly improves build speed, especially since we're mostly compiling llvm.
+        cmake .. -GNinja                                                               \
+            -DCMAKE_BUILD_TYPE=Release                                                 \
+            -DLLVM_PARALLEL_LINK_JOBS=1 ../cmake/superbuild                            \
+            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache    \
+            -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc                            \
+            -DOPTSCHEDSUPER_LLVM_EXTRA_CMAKE_ARGS='-DLLVM_ENABLE_ASSERTIONS=ON'        \
+            -DOPTSCHED_EXTRA_DEFINITIONS='-DIS_DEBUG'
+
+    - name: Build
+      working-directory: build-ci
+      run: |
+        # Zero out stats so we get an accurate report at the end.
+        ccache -z
+
+        # Build multiple times to avoid spurious problems with improperly set up CMake
+        # target dependencies by LLVM.
+        ninja || true
+        (ninja | grep -E -v '^-- Up-to-date: ') || true
+        (ninja | grep -E -v '^-- Up-to-date: ') || true
+        (ninja | grep -E -v '^-- Up-to-date: ') || true
+        (ninja | grep -E -v '^-- Up-to-date: ')
+
+    - name: Dump ccache Statistics
+      run: ccache -s
+
+    - name: Run tests
+      working-directory: build-ci
+      run: ctest -VV
 
   manual-build:
     needs: comment-triggered
@@ -265,5 +326,12 @@ jobs:
               needs.external-build.result == 'success' && '&#x2714; Passed' || '',
               needs.external-build.result == 'failure' && '&#x274C; Failed' || '',
               (needs.external-build.result != 'success' && needs.external-build.result != 'failure') && 'Skipped' || ''
+            )
+          }}
+          ${{
+            format('| Super Build | {0}{1}{2} |',
+              needs.super-build.result == 'success' && '&#x2714; Passed' || '',
+              needs.super-build.result == 'failure' && '&#x274C; Failed' || '',
+              (needs.super-build.result != 'success' && needs.super-build.result != 'failure') && 'Skipped' || ''
             )
           }}
